### PR TITLE
draft circle configuration (type checks the dk proof library)

### PR DESCRIPTION
**Pull request by rprimet**

### CODE REVIEW

**Comment by francoisthire** [comment]
Why did you choose to use CircleCI than Travis?

**Comment by rprimet** [comment]
Hi François,

Right now, we are not sure of whatever solution is the best, and hence are exploring our options. We started with CircleCI because, among other things,

- it seems to be easy to get started from a base docker image (helps keeping our jobs isolated/reproducible)
- Circle provides a local CLI that lets one validate their configuration and run jobs locally and is easy to set up (Travis can do a part of that too, but it seems way more involved)
- It seems to have a good integration with Github through the checks API

Other options that we are also considering are Travis, and Gitlab CI (which would let us provide our own build machines -- this may come in handy during deployment).

But as I said, we picked what we thought was a sensible starting point to explore / prototype.

Is there any compelling reason for using something else? (Travis or otherwise?)

**Comment by francoisthire** [comment]
I can check that everything is OK? How can I run CircleCI?

**Comment by rprimet** [comment]
You can go to circleci.com, log in using your github credentials and enable circleCI for the Deducteam/Logipedia project. Not sure whether this will run a CI job for the current pull request, but you can check that it completed correctly on the branch [here](https://circleci.com/gh/rprimet/Logipedia/3).

Unfortunately I do not have the credentials to enable CircleCI on the Deducteam org.

If you want to merge the branch locally and run the job on your own machine, instructions are available [here](https://circleci.com/docs/2.0/local-cli/) (but I can also fix issues if they arise after the merge).

**Comment by francoisthire** [comment]
It should be fine now, can you confirm?

Le mar. 28 mai 2019 à 16:36, Romain Primet <notifications@github.com> a
écrit :

**Comment by rprimet** [comment]
Yep, thanks! Although I cannot see the builds for the Dedukteam org except by manual probing...e.g. going to https://circleci.com/gh/Deducteam/Logipedia/2

But that's something I should try to figure out.

Would it be also possible to [enable Github checks](https://circleci.com/docs/2.0/enable-checks/) for Circle too? This would bring a nicer integration (e.g. we'd get build results attached to pull requests...)

Thanks!

**Pull request merged**
