### PR TITLE
Clean some cruft

### PR DESCRIPTION
**Pull request by rprimet**
A branch to remove some outdated content and files that were erroneously checked into source control.

### CODE REVIEW

**Comment by francoisthire** [comment]
Can you merge master to check if the "check tab" of GitHub UI is working please?

**Comment by rprimet** [comment]
Did that, does not seem to build PRs from forked repositories by default. Could you try to enable [this setting](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories) for the project?

**Comment by francoisthire** [comment]
Yes, it was checked already. I will let you admin so that you can see be yourself.

**Comment by francoisthire** [comment]
I still don't see the CircleCI integration for this PR, is this normal?

**Comment by rprimet** [comment]
Checks depend on v2.1+ for the config file format; this is now fixed and circle checks are shown.

**Pull request merged**
